FROM node:20 AS base

WORKDIR /app
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ARG NODE_ENV="development"

RUN corepack enable



FROM base AS dependencies

COPY package.json pnpm-lock.yaml ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile



FROM base AS dev

EXPOSE 5173
COPY --from=dependencies /app/node_modules /app/node_modules

CMD ["pnpm", "dev"]
