name: todo-list-dev

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.dev.backend
    image: chocobe/todos-dev-backend
    ports:
      - 3005:3001
    volumes:
      - ../backend:/app
      - /app/node_modules
    networks:
      - todos-network

networks:
  todos-network:
