FROM node:20 as base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app



FROM base as dependencies

COPY package.json pnpm-lock.yaml ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile



FROM base as dev

EXPOSE 3001
WORKDIR /app
COPY --from=dependencies /app/node_modules /app/node_modules

CMD ["pnpm", "dev"]
