name: todo-list-dev

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.dev.frontend
    image: chocobe/todos-dev-frontend
    ports:
      - 3001:5173
    volumes:
      - ../frontend:/app
      - /app/node_modules
    networks:
      - todos-network

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.dev.backend
    image: chocobe/todos-dev-backend
    ports:
      - 3002:3001
    volumes:
      - ../backend:/app
      - /app/node_modules
    networks:
      - todos-network
    env_file:
      - ../backend/.env.development

  database:
    image: mysql:9.4
    environment:
      MYSQL_ROOT_PASSWORD: hello-mysql
      MYSQL_DATABASE: miles-database
    volumes:
      - ../dev-database/database-volume:/var/lib/mysql
      - ../dev-database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todos-network

networks:
  todos-network:
