name: todo-list-dev

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.dev.backend
    image: chocobe/todos-dev-backend
    ports:
      - 3005:3001
    volumes:
      - ../backend:/app
      - /app/node_modules
    networks:
      - todos-network

  database:
    image: mysql:9.4
    ports:
      - 3006:3306
    environment:
      MYSQL_ROOT_PASSWORD: hello-mysql
      MYSQL_DATABASE: miles-database
    networks:
      - todos-network

networks:
  todos-network:
